-- Keep the default purchasable catalog in the versioned database history.
-- `mark_package.id` is generated by the application schema, not by a database
-- default, so these IDs must remain stable for this migration to be replayable.
INSERT INTO "mark_package" ("id", "code", "name", "marks", "price_idr", "is_active")
VALUES
  ('24e35c1b-cbcd-4c0b-9336-a94003a48984', 'starter', 'Starter Pack', 50, 312500, true),
  ('2d78227d-4f58-4936-ad1c-0a19281ff5e3', 'learner', 'Learner Pack', 120, 690000, true),
  ('abae487f-62a5-4d2a-ac9d-377a76c2413c', 'explorer', 'Explorer Pack', 200, 1070000, true),
  ('355c27c4-92fe-4e61-9e5b-b446e17d78c2', 'pioneer', 'Pioneer Pack', 400, 2000000, true)
ON CONFLICT ("code") DO UPDATE SET
  "name" = EXCLUDED."name",
  "marks" = EXCLUDED."marks",
  "price_idr" = EXCLUDED."price_idr",
  "updated_at" = now();
