import { BOOKING_STATE, type BookingState } from "./booking-state.types";

const TRANSITIONS: Record<
  BookingState,
  { to: BookingState[]; auto?: boolean }
> = {
  [BOOKING_STATE.AWAITING_TUTOR_REVIEW]: {
    to: [
      BOOKING_STATE.DECLINED,
      BOOKING_STATE.CONFIRMED,
      BOOKING_STATE.RESCHEDULE_PROPOSED,
      BOOKING_STATE.AWAITING_RECONFIRMATION,
      BOOKING_STATE.EXPIRED,
      BOOKING_STATE.CANCELLED,
      BOOKING_STATE.LATE_CANCELLED,
    ],
  },
  [BOOKING_STATE.AWAITING_PARTICIPANT_CONFIRMATION]: {
    to: [
      BOOKING_STATE.AWAITING_RECONFIRMATION,
      BOOKING_STATE.AWAITING_TUTOR_REVIEW,
      BOOKING_STATE.EXPIRED,
    ],
  },
  [BOOKING_STATE.AWAITING_RECONFIRMATION]: {
    to: [
      BOOKING_STATE.AWAITING_TUTOR_REVIEW,
      BOOKING_STATE.CONFIRMED,
      BOOKING_STATE.EXPIRED,
    ],
  },
  [BOOKING_STATE.AWAITING_ADMIN_ROOM_APPROVAL]: {
    to: [
      BOOKING_STATE.SCHEDULED,
      BOOKING_STATE.RESCHEDULE_PROPOSED,
      BOOKING_STATE.AWAITING_RECONFIRMATION,
      BOOKING_STATE.CANCELLED,
    ],
  },
  [BOOKING_STATE.CONFIRMED]: {
    to: [
      BOOKING_STATE.RESCHEDULE_PROPOSED,
      BOOKING_STATE.AWAITING_ADMIN_ROOM_APPROVAL,
      BOOKING_STATE.SCHEDULED,
      BOOKING_STATE.AWAITING_RECONFIRMATION,
      BOOKING_STATE.RESCHEDULE_PROPOSED,
      BOOKING_STATE.CANCELLED,
      BOOKING_STATE.LATE_CANCELLED,
    ],
  },
  [BOOKING_STATE.SCHEDULED]: {
    to: [
      BOOKING_STATE.RESCHEDULE_PROPOSED,
      BOOKING_STATE.COMPLETED,
      BOOKING_STATE.AWAITING_RECONFIRMATION,
      BOOKING_STATE.RESCHEDULE_PROPOSED,
      BOOKING_STATE.CANCELLED,
      BOOKING_STATE.LATE_CANCELLED,
      BOOKING_STATE.NO_SHOW,
    ],
  },
  [BOOKING_STATE.COMPLETED]: { to: [] },
  [BOOKING_STATE.DECLINED]: { to: [] },
  [BOOKING_STATE.CANCELLED]: { to: [] },
  [BOOKING_STATE.LATE_CANCELLED]: { to: [] },
  [BOOKING_STATE.NO_SHOW]: { to: [] },
  [BOOKING_STATE.EXPIRED]: { to: [] },
  [BOOKING_STATE.RESCHEDULE_PROPOSED]: {
    to: [
      BOOKING_STATE.AWAITING_TUTOR_REVIEW,
      BOOKING_STATE.CONFIRMED,
      BOOKING_STATE.SCHEDULED,
      BOOKING_STATE.AWAITING_ADMIN_ROOM_APPROVAL,
      BOOKING_STATE.AWAITING_RECONFIRMATION,
      BOOKING_STATE.DECLINED,
      BOOKING_STATE.EXPIRED,
    ],
  },
};

export { TRANSITIONS };

export function canTransition(
  from: BookingState | null,
  to: BookingState,
): boolean {
  if (!from) return true;
  return TRANSITIONS[from]?.to.includes(to) ?? false;
}
