/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTutorsRouteImport } from './routes/_app.tutors'
import { Route as AppTodosRouteImport } from './routes/_app.todos'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppBalanceRouteImport } from './routes/_app.balance'
import { Route as AppAchivementsRouteImport } from './routes/_app.achivements'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTutorsRoute = AppTutorsRouteImport.update({
  id: '/tutors',
  path: '/tutors',
  getParentRoute: () => AppRoute,
} as any)
const AppTodosRoute = AppTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBalanceRoute = AppBalanceRouteImport.update({
  id: '/balance',
  path: '/balance',
  getParentRoute: () => AppRoute,
} as any)
const AppAchivementsRoute = AppAchivementsRouteImport.update({
  id: '/achivements',
  path: '/achivements',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/achivements': typeof AppAchivementsRoute
  '/balance': typeof AppBalanceRoute
  '/dashboard': typeof AppDashboardRoute
  '/todos': typeof AppTodosRoute
  '/tutors': typeof AppTutorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/achivements': typeof AppAchivementsRoute
  '/balance': typeof AppBalanceRoute
  '/dashboard': typeof AppDashboardRoute
  '/todos': typeof AppTodosRoute
  '/tutors': typeof AppTutorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/achivements': typeof AppAchivementsRoute
  '/_app/balance': typeof AppBalanceRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/todos': typeof AppTodosRoute
  '/_app/tutors': typeof AppTutorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/achivements'
    | '/balance'
    | '/dashboard'
    | '/todos'
    | '/tutors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/achivements'
    | '/balance'
    | '/dashboard'
    | '/todos'
    | '/tutors'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/achivements'
    | '/_app/balance'
    | '/_app/dashboard'
    | '/_app/todos'
    | '/_app/tutors'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tutors': {
      id: '/_app/tutors'
      path: '/tutors'
      fullPath: '/tutors'
      preLoaderRoute: typeof AppTutorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/todos': {
      id: '/_app/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof AppTodosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/balance': {
      id: '/_app/balance'
      path: '/balance'
      fullPath: '/balance'
      preLoaderRoute: typeof AppBalanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/achivements': {
      id: '/_app/achivements'
      path: '/achivements'
      fullPath: '/achivements'
      preLoaderRoute: typeof AppAchivementsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAchivementsRoute: typeof AppAchivementsRoute
  AppBalanceRoute: typeof AppBalanceRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppTodosRoute: typeof AppTodosRoute
  AppTutorsRoute: typeof AppTutorsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAchivementsRoute: AppAchivementsRoute,
  AppBalanceRoute: AppBalanceRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppTodosRoute: AppTodosRoute,
  AppTutorsRoute: AppTutorsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
